### ISSUE TITLE
embed 

### ISSUE THREAD

**Issue by tduck3** [V86760/simple-music-bot#1]
on the last line it hase to be embeds not embed 😉

**Comment by V86760** [comment]
Hey! Thanks for the comment letting me know there's an issue! What do you mean by last line? Are you trying to run a command?

**Comment by tduck3** [comment]
Moment i will search which line it is

**Comment by tduck3** [comment]
index 147

**Comment by tduck3** [comment]
![D03FD8D5-4CFF-4A46-B115-14F954AFA654](https://user-images.githubusercontent.com/98735434/157821047-2bd65094-4392-42d5-a6ab-f1c8fa960562.jpeg)

**Comment by V86760** [comment]
Sweet! Thank you, I'm working on a few more commands right now! I'll release an update fixing this shortly!

**Comment by V86760** [comment]
If you add an s to it(embeds) You can fix it while you wait for this update!

**Comment by tduck3** [comment]
can you add the leave command that the bot is leaving the call

**Comment by V86760** [comment]
Absolutely

**Comment by tduck3** [comment]
thx ☺️

**Comment by V86760** [comment]
Of course!

**Comment by tduck3** [comment]
And can you add emoji link botify when you click and a emoji it stops the music

**Comment by V86760** [comment]
Can do

**Comment by tduck3** [comment]
only your code works on my bot because i dont use events

**Comment by tduck3** [comment]
And i am really bad in making music bots

**Comment by tduck3** [comment]
When do you think the next update is and have you discord

**Comment by V86760** [comment]
Will be out shortly, and yes I do: V8.#6760

**Comment by tduck3** [comment]
I have add you as friend 😉

**Comment by tduck3** [comment]
the resume command is also bugged

**Comment by V86760** [comment]
Gotta, sent you a message about it on discord !

**Comment by tduck3** [comment]
Oke
